import { useEffect, useState } from 'react';
import { api } from './api';

type Customer = { id:number|string; customer_number:string; first_name:string; last_name:string; phone:string; email?:string|null; status:string; billing_type:string };
type Form = { first_name:string; last_name:string; phone:string; email:string; billing_type:'prepaid'|'postpaid'; status:'active'|'suspended'|'disconnected'; notes:string };
const empty:Form={first_name:'',last_name:'',phone:'',email:'',billing_type:'postpaid',status:'active',notes:''};

export default function CustomersPage() {
 const [customers,setCustomers]=useState<Customer[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false); const [form,setForm]=useState<Form>(empty);
 async function load(term=search){setLoading(true);setError('');try{const qs=term?`?search=${encodeURIComponent(term)}`:'';const data=await api<{data:Customer[]}>('/customers'+qs);setCustomers(data.data??[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load customers.');}finally{setLoading(false);}}
 useEffect(()=>{load('');},[]);
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await api('/customers',{method:'POST',body:JSON.stringify(form)});setForm(empty);setShowForm(false);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to create customer.');}finally{setSaving(false);}}
 async function archive(id:string|number){if(!confirm('Archive this customer?'))return;try{await api(`/customers/${id}`,{method:'DELETE'});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to archive customer.');}}
 return <section className="content"><div className="welcome"><div><small>CUSTOMER MANAGEMENT</small><h2>Customers</h2><p>Live customer records from the billing database.</p></div><button className="primary" onClick={()=>setShowForm(true)}>+ Add Customer</button></div>
 {error&&<p className="error">{error}</p>}
 {showForm&&<form className="panel formGrid" onSubmit={create}><h3>New customer</h3><label>First name<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Billing type<select value={form.billing_type} onChange={e=>setForm({...form,billing_type:e.target.value as Form['billing_type']})}><option value="postpaid">Postpaid</option><option value="prepaid">Prepaid</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Form['status']})}><option value="active">Active</option><option value="suspended">Suspended</option><option value="disconnected">Disconnected</option></select></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="formActions"><button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Create customer'}</button></div></form>}
 <div className="panel"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search number, name, phone or email"/><button onClick={()=>load()}>Search</button></div>{loading?<p>Loading customers…</p>:customers.length===0?<p>No customers found.</p>:<div className="tableWrap"><table><thead><tr><th>Number</th><th>Customer</th><th>Phone</th><th>Billing</th><th>Status</th><th>Action</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td>{c.customer_number}</td><td>{c.first_name} {c.last_name}</td><td>{c.phone}</td><td>{c.billing_type}</td><td><span className="statusBadge">{c.status}</span></td><td><button className="linkButton" onClick={()=>archive(c.id)}>Archive</button></td></tr>)}</tbody></table></div>}</div></section>;
}
