import { useEffect, useState } from 'react';
import { api } from './api';

type Package={id:number|string;code:string;name:string;description?:string|null;download_mbps:number;upload_mbps:number;price:string|number;currency:string;billing_cycle:string;data_limit_gb?:number|null;fair_usage_gb?:number|null;is_active:boolean};
type Form={code:string;name:string;description:string;download_mbps:string;upload_mbps:string;price:string;currency:string;billing_cycle:string;data_limit_gb:string;fair_usage_gb:string;is_active:boolean};
const empty:Form={code:'',name:'',description:'',download_mbps:'',upload_mbps:'',price:'',currency:'KES',billing_cycle:'monthly',data_limit_gb:'',fair_usage_gb:'',is_active:true};
export default function PackagesPage(){const [items,setItems]=useState<Package[]>([]),[search,setSearch]=useState(''),[show,setShow]=useState(false),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
async function load(term=search){setLoading(true);setError('');try{const q=term?`?search=${encodeURIComponent(term)}`:'';const r=await api<{data:Package[]}>('/packages'+q);setItems(r.data??[])}catch(e){setError(e instanceof Error?e.message:'Unable to load packages.')}finally{setLoading(false)}}
useEffect(()=>{load('')},[]);
async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await api('/packages',{method:'POST',body:JSON.stringify({...form,download_mbps:Number(form.download_mbps),upload_mbps:Number(form.upload_mbps),price:Number(form.price),data_limit_gb:form.data_limit_gb?Number(form.data_limit_gb):null,fair_usage_gb:form.fair_usage_gb?Number(form.fair_usage_gb):null})});setForm(empty);setShow(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create package.')}finally{setSaving(false)}}
async function archive(id:string|number){if(!confirm('Archive this package?'))return;try{await api(`/packages/${id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to archive package.')}}
const set=(k:keyof Form,v:any)=>setForm({...form,[k]:v});
return <section className="content"><div className="welcome"><div><small>PRODUCT CATALOGUE</small><h2>Packages</h2><p>Manage the plans used by subscriptions and network provisioning.</p></div><button className="primary" onClick={()=>setShow(true)}>+ Add Package</button></div>{error&&<p className="error">{error}</p>}{show&&<form className="panel formGrid" onSubmit={create}><h3>New package</h3><label>Code<input required value={form.code} onChange={e=>set('code',e.target.value)}/></label><label>Name<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Download Mbps<input required type="number" min="1" value={form.download_mbps} onChange={e=>set('download_mbps',e.target.value)}/></label><label>Upload Mbps<input required type="number" min="1" value={form.upload_mbps} onChange={e=>set('upload_mbps',e.target.value)}/></label><label>Price<input required type="number" min="0" step="0.01" value={form.price} onChange={e=>set('price',e.target.value)}/></label><label>Currency<input maxLength={3} value={form.currency} onChange={e=>set('currency',e.target.value.toUpperCase())}/></label><label>Billing cycle<select value={form.billing_cycle} onChange={e=>set('billing_cycle',e.target.value)}><option>daily</option><option>weekly</option><option>monthly</option><option>quarterly</option><option>annual</option></select></label><label>Data limit GB<input type="number" min="1" value={form.data_limit_gb} onChange={e=>set('data_limit_gb',e.target.value)}/></label><label>Fair usage GB<input type="number" min="1" value={form.fair_usage_gb} onChange={e=>set('fair_usage_gb',e.target.value)}/></label><label className="full">Description<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label><div className="formActions"><button type="button" onClick={()=>setShow(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Create package'}</button></div></form>}
<div className="panel"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search package code or name"/><button onClick={()=>load()}>Search</button></div>{loading?<p>Loading packages…</p>:items.length===0?<p>No packages found.</p>:<div className="tableWrap"><table><thead><tr><th>Code</th><th>Package</th><th>Speed</th><th>Price</th><th>Cycle</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.name}</td><td>{p.download_mbps}/{p.upload_mbps} Mbps</td><td>{p.currency} {p.price}</td><td>{p.billing_cycle}</td><td><span className="statusBadge">{p.is_active?'active':'inactive'}</span></td><td><button className="linkButton" onClick={()=>archive(p.id)}>Archive</button></td></tr>)}</tbody></table></div>}</div></section>}
