import { useEffect, useState } from 'react';
import { api } from './api';

type Customer={id:number;customer_number:string;first_name:string;last_name:string};
type Package={id:number;code:string;name:string;price:string|number;billing_cycle:string};
type Subscription={id:number;subscription_number:string;status:string;starts_at:string;next_billing_at:string;auto_renew:boolean;recurring_price:string|number;currency:string;customer:Customer;package:Package};
export default function SubscriptionsPage(){const [items,setItems]=useState<Subscription[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[packages,setPackages]=useState<Package[]>([]),[search,setSearch]=useState(''),[show,setShow]=useState(false),[customerId,setCustomerId]=useState(''),[packageId,setPackageId]=useState(''),[startsAt,setStartsAt]=useState(new Date().toISOString().slice(0,10)),[autoRenew,setAutoRenew]=useState(true),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
async function load(term=search){setLoading(true);setError('');try{const q=term?`?search=${encodeURIComponent(term)}`:'';const r=await api<{data:Subscription[]}>('/subscriptions'+q);setItems(r.data??[])}catch(e){setError(e instanceof Error?e.message:'Unable to load subscriptions.')}finally{setLoading(false)}}
async function loadChoices(){try{const [c,p]=await Promise.all([api<{data:Customer[]}>('/customers'),api<{data:Package[]}>('/packages')]);setCustomers(c.data??[]);setPackages(p.data??[])}catch(e){setError(e instanceof Error?e.message:'Unable to load customers and packages.')}}
useEffect(()=>{load('');loadChoices()},[]);
async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await api('/subscriptions',{method:'POST',body:JSON.stringify({customer_id:Number(customerId),package_id:Number(packageId),starts_at:startsAt,auto_renew:autoRenew})});setShow(false);setCustomerId('');setPackageId('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create subscription.')}finally{setSaving(false)}}
async function action(id:number,op:'activate'|'suspend'|'cancel'){if(op==='cancel'&&!confirm('Cancel this subscription?'))return;try{await api(`/subscriptions/${id}/${op}`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update subscription.')}}
return <section className="content"><div className="welcome"><div><small>SERVICE CONTRACTS</small><h2>Subscriptions</h2><p>Connect customers to packages and billing cycles.</p></div><button className="primary" onClick={()=>setShow(true)}>+ New Subscription</button></div>{error&&<p className="error">{error}</p>}{show&&<form className="panel formGrid" onSubmit={create}><h3>New subscription</h3><label>Customer<select required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customer_number} — {c.first_name} {c.last_name}</option>)}</select></label><label>Package<select required value={packageId} onChange={e=>setPackageId(e.target.value)}><option value="">Select package</option>{packages.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name} ({p.price} / {p.billing_cycle})</option>)}</select></label><label>Start date<input required type="date" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label className="check"><input type="checkbox" checked={autoRenew} onChange={e=>setAutoRenew(e.target.checked)}/> Auto renew</label><div className="formActions"><button type="button" onClick={()=>setShow(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Creating…':'Create subscription'}</button></div></form>}
<div className="panel"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search subscription, customer or package"/><button onClick={()=>load()}>Search</button></div>{loading?<p>Loading subscriptions…</p>:items.length===0?<p>No subscriptions found.</p>:<div className="tableWrap"><table><thead><tr><th>Subscription</th><th>Customer</th><th>Package</th><th>Next billing</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(s=><tr key={s.id}><td>{s.subscription_number}</td><td>{s.customer?.customer_number} — {s.customer?.first_name} {s.customer?.last_name}</td><td>{s.package?.code} — {s.package?.name}</td><td>{s.next_billing_at}</td><td><span className="statusBadge">{s.status}</span></td><td>{s.status==='active'&&<button className="linkButton" onClick={()=>action(s.id,'suspend')}>Suspend</button>}{s.status==='suspended'&&<button className="linkButton" onClick={()=>action(s.id,'activate')}>Activate</button>}{s.status!=='cancelled'&&<button className="linkButton" onClick={()=>action(s.id,'cancel')}>Cancel</button>}</td></tr>)}</tbody></table></div>}</div></section>}
